In [1]:
# Import packages

import pandas as pd 
import numpy as np 
import os

C:\Users\imacd_0odruq3\anaconda3\lib\site-packages\pandas\core\computation\expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [2]:
# Import data

rb = pd.read_csv('data/04_initial_rushing_values.csv')
rb = rb.drop(columns = ['Unnamed: 0'])
pass_def = pd.read_csv('data/04_initial_pass_defense_values.csv')
pass_def = pass_def.drop(columns = ['Unnamed: 0'])
rush_def = pd.read_csv('data/04_initial_rush_defense_values.csv')
rush_def = rush_def.drop(columns = ['Unnamed: 0'])
qb = pd.read_csv('data/04_initial_qb_values.csv')
qb = qb.drop(columns = ['Unnamed: 0'])
qb = qb.drop(columns = ['Unnamed: 0.1'])
st = pd.read_csv('data/04_initial_st_values.csv')
st = st.drop(columns = ['Unnamed: 0'])
extra = pd.read_csv('data/04_initial_extra_values.csv')
extra = extra.drop(columns = ['Unnamed: 0'])

In [3]:
extra

,season,week,team,opponent,score,opponent_score,total_plays,total_possession_time_seconds,pass_percentage,run_percentage,total_plays_standardized,total_possession_time_standardized,pass_percentage_standardized
0,2014,1,ARI,LAC,18,17,67.0,1909.0,0.606061,0.393939,0.122744,0.332304,0.156718
1,2014,1,ATL,NO,37,34,72.0,1878.0,0.632353,0.367647,0.683585,0.216847,0.405160
2,2014,1,BAL,CIN,16,23,87.0,1770.0,0.755814,0.244186,2.366110,-0.185390,1.571768
3,2014,1,BUF,CHI,23,20,59.0,1832.0,0.425926,0.574074,-0.774603,0.045524,-1.545411
4,2014,1,CAR,TB,20,14,71.0,2112.0,0.507463,0.492537,0.571417,1.088360,-0.774954
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4875,2022,21,KC,CIN,23,20,69.0,1971.0,0.696970,0.303030,0.347080,0.563217,1.015737
4876,2022,21,PHI,SF,31,7,71.0,2246.0,0.382353,0.617647,0.571417,1.587432,-1.957141
4877,2022,21,SF,PHI,7,31,45.0,1354.0,0.466667,0.533333,-2.344959,-1.734748,-1.160443
4878,2022,22,KC,PHI,38,35,55.0,1453.0,0.529412,0.470588,-1.223276,-1.366030,-0.567552
4879,2022,22,PHI,KC,35,38,74.0,2147.0,0.547945,0.452055,0.907922,1.218715,-0.392426

In [4]:
# Put data into one data frame that just has the game identifiers and value numbers

# qb = qb.copy()[['season', 'week', 'team', 'opponent', 'score', 'opponent_score', 'qb', 'qb_value', 'passing_value']]
qb = qb.copy()[['season', 'week', 'team', 'opponent', 'score', 'opponent_score', 'qb', 'passing_value']]
rb = rb.copy()[['season', 'week', 'team', 'opponent', 'score', 'opponent_score', 'rushing_value']]
pass_def = pass_def.copy()[['season', 'week', 'team', 'opponent', 'score', 'opponent_score', 'pass_def_value']]
rush_def = rush_def.copy()[['season', 'week', 'team', 'opponent', 'score', 'opponent_score', 'rush_def_value']]
st = st.copy()[['season', 'week', 'team', 'opponent', 'score', 'opponent_score', 'special_teams_value']]
extra = extra.copy()[['season', 'week', 'team', 'opponent', 'score', 'opponent_score', 'total_plays_standardized', 'total_possession_time_standardized', 'pass_percentage_standardized']]
df = qb.copy()
df = df.merge(rb).merge(pass_def).merge(rush_def).merge(st).merge(extra)
df = df.drop_duplicates()
df.head()

,season,week,team,opponent,score,opponent_score,qb,passing_value,rushing_value,pass_def_value,rush_def_value,special_teams_value,total_plays_standardized,total_possession_time_standardized,pass_percentage_standardized
0,2014,1,ARI,LAC,18,17,C. Palmer,0.366264,-1.119941,0.027688,1.468394,-0.996743,0.122744,0.332304,0.156718
1,2014,1,ATL,NO,37,34,M. Ryan,1.099442,0.747193,-0.559094,-1.005162,-0.243872,0.683585,0.216847,0.405160
2,2014,1,BAL,CIN,16,23,J. Flacco,-0.333911,0.246643,-0.765953,0.727127,-0.442100,2.366110,-0.185390,1.571768
3,2014,1,BUF,CHI,23,20,E. Manuel,-0.054710,0.919752,0.504718,-0.187514,0.780553,-0.774603,0.045524,-1.545411
4,2014,1,CAR,TB,20,14,D. Anderson,0.643818,-0.619783,0.982581,-0.392165,-0.725290,0.571417,1.088360,-0.774954

In [5]:
# Fix team names

# Move to helper functions

def fix_team_names(game, is_team=True):
    team_mapping = {
        'ARI':'Arizona Cardinals',
        'ATL':'Atlanta Falcons',
        'BAL':'Baltimore Ravens',
        'BUF':'Buffalo Bills',
        'CAR':'Carolina Panthers',
        'CHI':'Chicago Bears',
        'CIN':'Cincinnati Bengals',
        'CLE':'Cleveland Browns',
        'DAL':'Dallas Cowboys',
        'DEN':'Denver Broncos',
        'DET':'Detroit Lions',
        'GB':'Green Bay Packers',
        'HOU':'Houston Texans',
        'IND':'Indianapolis Colts',
        'JAX':'Jacksonville Jaguars',
        'KC':'Kansas City Chiefs',
        'OAK':'Las Vegas Raiders',
        'LV':'Las Vegas Raiders',
        'LAC':'Los Angeles Chargers',
        'LAR':'Los Angeles Rams',
        'LA':'Los Angeles Rams',
        'MIA':'Miami Dolphins',
        'MIN':'Minnesota Vikings',
        'NE':'New England Patriots',
        'NO':'New Orleans Saints',
        'NYG':'New York Giants',
        'NYJ':'New York Jets',
        'PHI':'Philadelphia Eagles',
        'PIT':'Pittsburgh Steelers',
        'SF':'San Francisco 49ers',
        'SEA':'Seattle Seahawks',
        'TB':'Tampa Bay Buccaneers',
        'TEN':'Tennessee Titans',
        'WSH':'Washington Football Team',
        'WAS':'Washington Football Team'
    }
    
    if is_team:
        return team_mapping[game['team']]
    
    else:
        return team_mapping[game['opponent']]
    
df['team_full'] = df.apply(lambda x: fix_team_names(x, is_team=True), axis=1)
df['opponent_full'] = df.apply(lambda x: fix_team_names(x, is_team=False), axis=1)
df.head()

,season,week,team,opponent,score,opponent_score,qb,passing_value,rushing_value,pass_def_value,rush_def_value,special_teams_value,total_plays_standardized,total_possession_time_standardized,pass_percentage_standardized,team_full,opponent_full
0,2014,1,ARI,LAC,18,17,C. Palmer,0.366264,-1.119941,0.027688,1.468394,-0.996743,0.122744,0.332304,0.156718,Arizona Cardinals,Los Angeles Chargers
1,2014,1,ATL,NO,37,34,M. Ryan,1.099442,0.747193,-0.559094,-1.005162,-0.243872,0.683585,0.216847,0.405160,Atlanta Falcons,New Orleans Saints
2,2014,1,BAL,CIN,16,23,J. Flacco,-0.333911,0.246643,-0.765953,0.727127,-0.442100,2.366110,-0.185390,1.571768,Baltimore Ravens,Cincinnati Bengals
3,2014,1,BUF,CHI,23,20,E. Manuel,-0.054710,0.919752,0.504718,-0.187514,0.780553,-0.774603,0.045524,-1.545411,Buffalo Bills,Chicago Bears
4,2014,1,CAR,TB,20,14,D. Anderson,0.643818,-0.619783,0.982581,-0.392165,-0.725290,0.571417,1.088360,-0.774954,Carolina Panthers,Tampa Bay Buccaneers

In [6]:
# Save raw data frame with values

df.to_csv('data/05_value_models_combined.csv')