In [2]:
# Import packages

import pandas as pd 
import numpy as np 
import os

In [2]:
# Import data

rb = pd.read_csv('data/04_seasontest_initial_rushing_values.csv')
rb = rb.drop(columns = ['Unnamed: 0'])
pass_def = pd.read_csv('data/04_seasontest_initial_pass_defense_values.csv')
pass_def = pass_def.drop(columns = ['Unnamed: 0'])
rush_def = pd.read_csv('data/04_seasontest_initial_rush_defense_values.csv')
rush_def = rush_def.drop(columns = ['Unnamed: 0'])
qb = pd.read_csv('data/04_seasontest_initial_qb_values.csv')
qb = qb.drop(columns = ['Unnamed: 0'])
qb = qb.drop(columns = ['Unnamed: 0.1'])
st = pd.read_csv('data/04_seasontest_initial_st_values.csv')
st = st.drop(columns = ['Unnamed: 0'])
extra = pd.read_csv('data/04_seasontest_initial_extra_values.csv')
extra = extra.drop(columns = ['Unnamed: 0'])

In [3]:
extra

,season,week,team,opponent,score,opponent_score,total_plays,total_possession_time_seconds,pass_percentage,run_percentage,total_plays_standardized,total_possession_time_standardized,pass_percentage_standardized
0,2022,1,ARI,KC,21,44,63.0,1518.0,0.671875,0.328125,-0.287243,-1.191364,0.868136
1,2022,1,ATL,NO,26,27,76.0,2024.0,0.457143,0.542857,1.220221,0.760677,-1.040346
2,2022,1,BAL,NYJ,24,9,54.0,1650.0,0.627451,0.372549,-1.330871,-0.682136,0.473307
3,2022,1,BUF,LA,31,10,59.0,1874.0,0.578947,0.421053,-0.751078,0.182009,0.042220
4,2022,1,CAR,CLE,24,26,51.0,1294.0,0.632653,0.367347,-1.678748,-2.055508,0.519542
...,...,...,...,...,...,...,...,...,...,...,...,...,...
563,2022,21,KC,CIN,23,20,69.0,1971.0,0.696970,0.303030,0.408510,0.556214,1.091171
564,2022,21,PHI,SF,31,7,71.0,2246.0,0.382353,0.617647,0.640427,1.617106,-1.705059
565,2022,21,SF,PHI,7,31,45.0,1354.0,0.466667,0.533333,-2.374500,-1.824041,-0.955701
566,2022,22,KC,PHI,38,35,55.0,1453.0,0.529412,0.470588,-1.214913,-1.442120,-0.398039
567,2022,22,PHI,KC,35,38,74.0,2147.0,0.547945,0.452055,0.988303,1.235185,-0.233319

In [4]:
# Put data into one data frame that just has the game identifiers and value numbers

# qb = qb.copy()[['season', 'week', 'team', 'opponent', 'score', 'opponent_score', 'qb', 'qb_value', 'passing_value']]
qb = qb.copy()[['season', 'week', 'team', 'opponent', 'score', 'opponent_score', 'qb', 'passing_value']]
rb = rb.copy()[['season', 'week', 'team', 'opponent', 'score', 'opponent_score', 'rushing_value']]
pass_def = pass_def.copy()[['season', 'week', 'team', 'opponent', 'score', 'opponent_score', 'pass_def_value']]
rush_def = rush_def.copy()[['season', 'week', 'team', 'opponent', 'score', 'opponent_score', 'rush_def_value']]
st = st.copy()[['season', 'week', 'team', 'opponent', 'score', 'opponent_score', 'special_teams_value']]
extra = extra.copy()[['season', 'week', 'team', 'opponent', 'score', 'opponent_score', 'total_plays_standardized', 'total_possession_time_standardized', 'pass_percentage_standardized']]
df = qb.copy()
df = df.merge(rb).merge(pass_def).merge(rush_def).merge(st).merge(extra)
df = df.drop_duplicates()
df.head()

,season,week,team,opponent,score,opponent_score,qb,passing_value,rushing_value,pass_def_value,rush_def_value,special_teams_value,total_plays_standardized,total_possession_time_standardized,pass_percentage_standardized
0,2022,1,ARI,KC,21,44,K. Murray,0.022362,0.456225,-2.423499,0.149580,0.252907,-0.287243,-1.191364,0.868136
1,2022,1,ATL,NO,26,27,M. Mariota,-0.112911,0.037099,-0.090737,-1.034817,1.055577,1.220221,0.760677,-1.040346
2,2022,1,BAL,NYJ,24,9,L. Jackson,0.447970,-0.212488,0.634443,0.655233,1.591348,-1.330871,-0.682136,0.473307
3,2022,1,BUF,LA,31,10,J. Allen,1.414945,-0.550318,1.304938,0.187208,0.478257,-0.751078,0.182009,0.042220
4,2022,1,CAR,CLE,24,26,B. Mayfield,-0.203192,0.703623,0.723040,-1.476490,-0.429324,-1.678748,-2.055508,0.519542

In [21]:
# Manual Input of current week games

# UPDATE THIS before each run

current_week = 1
current_season = 2023

qbs = pd.read_csv('data/03_seasontest_team_primary_qb_lookup_table.csv')

# Fix team names

# Move to helper functions

def fix_team_names(team_abrv):
    team_mapping = {
        'ARI':'Arizona Cardinals',
        'ATL':'Atlanta Falcons',
        'BAL':'Baltimore Ravens',
        'BUF':'Buffalo Bills',
        'CAR':'Carolina Panthers',
        'CHI':'Chicago Bears',
        'CIN':'Cincinnati Bengals',
        'CLE':'Cleveland Browns',
        'DAL':'Dallas Cowboys',
        'DEN':'Denver Broncos',
        'DET':'Detroit Lions',
        'GB':'Green Bay Packers',
        'HOU':'Houston Texans',
        'IND':'Indianapolis Colts',
        'JAX':'Jacksonville Jaguars',
        'KC':'Kansas City Chiefs',
        'OAK':'Las Vegas Raiders',
        'LV':'Las Vegas Raiders',
        'LAC':'Los Angeles Chargers',
        'LAR':'Los Angeles Rams',
        'LA':'Los Angeles Rams',
        'MIA':'Miami Dolphins',
        'MIN':'Minnesota Vikings',
        'NE':'New England Patriots',
        'NO':'New Orleans Saints',
        'NYG':'New York Giants',
        'NYJ':'New York Jets',
        'PHI':'Philadelphia Eagles',
        'PIT':'Pittsburgh Steelers',
        'SF':'San Francisco 49ers',
        'SEA':'Seattle Seahawks',
        'TB':'Tampa Bay Buccaneers',
        'TEN':'Tennessee Titans',
        'WSH':'Washington Football Team',
        'WAS':'Washington Football Team'
    }

    return team_mapping[team_abrv]

    
qbs['team_full'] = qbs.apply(lambda x: fix_team_names(x.team), axis=1)

if current_week == 1:
    check_week = 18
    check_season = current_season-1
    
else:
    check_week = current_week - 1
    check_season = current_season

current_week_qbs = qbs[(qbs.season == check_season) & (qbs.week == check_week)]
current_week_qbs = current_week_qbs[['season', 'week', 'team', 'team_full', 'qb']]
current_week_qbs['week'] = current_week
current_week_qbs['season'] = current_season

qb_dict = {game['team_full']:game['qb'] for index, game in current_week_qbs.iterrows()}

# QB Updates, if necessary

# qb_dict['Arizona Cardinals'] = 'Kyler Murray'
# qb_dict['Atlanta Falcons'] = 'Marcus Mariota'
# qb_dict['Baltimore Ravens'] = 'Lamar Jackson'
# qb_dict['Buffalo Bills'] = 'Josh Allen'
# qb_dict['Carolina Panthers'] = 'P.J. Walker'
# qb_dict['Chicago Bears'] = 'Trevor Siemian'
# qb_dict['Cincinnati Bengals'] = 'Joe Burrow'
# qb_dict['Cleveland Browns'] = 'Jacoby Brissett'
# qb_dict['Dallas Cowboys'] = 'Dak Prescott'
# qb_dict['Denver Broncos'] = 'Russell Wilson'
# qb_dict['Detroit Lions'] = 'Jared Goff'
# qb_dict['Green Bay Packers'] = 'Aaron Rodgers'
# qb_dict['Houston Texans'] = 'Kyle Allen'
# qb_dict['Indianapolis Colts'] = 'Matt Ryan'
# qb_dict['Jacksonville Jaguars'] = 'Trevor Lawrence'
# qb_dict['Kansas City Chiefs'] = 'Patrick Mahomes'
# qb_dict['Las Vegas Raiders'] = 'Derek Carr'
# qb_dict['Los Angeles Chargers'] = 'Justin Herbert'
# qb_dict['Los Angeles Rams'] = 'Matthew Stafford'
# qb_dict['Miami Dolphins'] = 'Tua Tagovailoa'
# qb_dict['Minnesota Vikings'] = 'Kirk Cousins'
# qb_dict['New England Patriots'] = 'Mac Jones'
# qb_dict['New Orleans Saints'] = 'Andy Dalton'
# qb_dict['New York Giants'] = 'Daniel Jones'
# qb_dict['New York Jets'] = 'Mike White'
# qb_dict['Philadelphia Eagles'] = 'Jalen Hurts'
# qb_dict['Pittsburgh Steelers'] = 'Kenny Pickett'
# qb_dict['San Francisco 49ers'] = 'Jimmy Garoppolo'
# qb_dict['Seattle Seahawks'] = 'Geno Smith'
# qb_dict['Tampa Bay Buccaneers'] = 'Tom Brady'
# qb_dict['Tennessee Titans'] = 'Ryan Tannehill'
# qb_dict['Washington Football Team'] = 'Taylor Heinicke'

# CHECK: Are qbs correct?

# IF NOT, update in previous step. Otherwise, good to go

# for team, qb in qb_dict.items():
#     print('{}: {}'.format(team, qb))
#     print()

# Manually Inputted
# While not ideal, manually inputting the odds/games in doesn't take too much time/effort
# In the future, want to create a web scraping bot to automate getting the necessary odds and game data
# For now, this will have to do

# Column Order
# 'season', 'week', 'away', 'home', 'away_moneyline', 'home_moneyline', 'away_spread', 'over_under'

manual_input = {
    '{}{}{}'.format(current_season, current_week, 1): [current_season, current_week, 'DET','KC',
                                                      -225, 185, 4.5, 52.5]
#     '{}{}{}'.format(current_season, current_week, 2): [current_season, current_week, 'NYG','DAL',
#                                                       350, -435, 10, -10, 45.5],
#     '{}{}{}'.format(current_season, current_week, 3): [current_season, current_week, 'NE','MIN',
#                                                       115, -135, 2.5, -2.5, 42.5],
#     '{}{}{}'.format(current_season, current_week, 4): [current_season, current_week, 'HOU','MIA',
#                                                       550, -750, 13.5, -13.5, 47],
#     '{}{}{}'.format(current_season, current_week, 5): [current_season, current_week, 'BAL','JAX',
#                                                       -195, 165, -3.5, 3.5, 43.5],
#     '{}{}{}'.format(current_season, current_week, 6): [current_season, current_week, 'CHI','NYJ',
#                                                       215, -255, 6, -6, 38.5],
#     '{}{}{}'.format(current_season, current_week, 7): [current_season, current_week, 'CIN','TEN',
#                                                       -150, 130, -2.5, 2.5, 42.5],
#     '{}{}{}'.format(current_season, current_week, 8): [current_season, current_week, 'ATL','WAS',
#                                                       170, -200, 4.5, -4.5, 40.5],
#     '{}{}{}'.format(current_season, current_week, 9): [current_season, current_week, 'DEN','CAR',
#                                                       -130, 110, -1.5, 1.5, 36],
#     '{}{}{}'.format(current_season, current_week, 10): [current_season, current_week, 'TB','CLE',
#                                                       -180, 155, -3.5, 3.5, 42],
#     '{}{}{}'.format(current_season, current_week, 11): [current_season, current_week, 'LV','SEA',
#                                                       165, -195, 3.5, -3.5, 48],
#     '{}{}{}'.format(current_season, current_week, 12): [current_season, current_week, 'LAC','ARI',
#                                                       -175, 150, -3, 3, 48],
#     '{}{}{}'.format(current_season, current_week, 13): [current_season, current_week, 'LAR','KC',
#                                                       750, -1150, 15.5, -15.5, 42],
#     '{}{}{}'.format(current_season, current_week, 14): [current_season, current_week, 'NO','SF',
#                                                       330, -410, 9.5, -9.5, 43.5],
#     '{}{}{}'.format(current_season, current_week, 15): [current_season, current_week, 'GB','PHI',
#                                                       245, -295, 6.5, -6.5, 43.5]
#     '{}{}{}'.format(current_season, current_week, 16): [current_season, current_week, 'LV','KC',
#                                                       265, -320, 7, -7, 51.5]
}

manual_input

current_week_data = pd.DataFrame.from_dict(manual_input, orient='index',
                                          columns = ['season', 'week', 'away', 'home', 
                                                    'away_moneyline', 'home_moneyline', 
                                                    'away_spread', 'over_under'])
current_week_data['home_full_name'] = current_week_data.apply(lambda x: fix_team_names(x.home), axis=1)
current_week_data['away_full_name'] = current_week_data.apply(lambda x: fix_team_names(x.away), axis=1)
current_week_data['home_qb'] = current_week_data.apply(lambda x: qb_dict[x.home_full_name], axis=1)
current_week_data['away_qb'] = current_week_data.apply(lambda x: qb_dict[x.away_full_name], axis=1)

current_week_data

,season,week,away,home,away_moneyline,home_moneyline,away_spread,over_under,home_full_name,away_full_name,home_qb,away_qb
202311,2023,1,DET,KC,-225,185,4.5,52.5,Kansas City Chiefs,Detroit Lions,P. Mahomes,J. Goff

In [5]:
# Fix team names

# Move to helper functions

def fix_team_names(game, is_team=True):
    team_mapping = {
        'ARI':'Arizona Cardinals',
        'ATL':'Atlanta Falcons',
        'BAL':'Baltimore Ravens',
        'BUF':'Buffalo Bills',
        'CAR':'Carolina Panthers',
        'CHI':'Chicago Bears',
        'CIN':'Cincinnati Bengals',
        'CLE':'Cleveland Browns',
        'DAL':'Dallas Cowboys',
        'DEN':'Denver Broncos',
        'DET':'Detroit Lions',
        'GB':'Green Bay Packers',
        'HOU':'Houston Texans',
        'IND':'Indianapolis Colts',
        'JAX':'Jacksonville Jaguars',
        'KC':'Kansas City Chiefs',
        'OAK':'Las Vegas Raiders',
        'LV':'Las Vegas Raiders',
        'LAC':'Los Angeles Chargers',
        'LAR':'Los Angeles Rams',
        'LA':'Los Angeles Rams',
        'MIA':'Miami Dolphins',
        'MIN':'Minnesota Vikings',
        'NE':'New England Patriots',
        'NO':'New Orleans Saints',
        'NYG':'New York Giants',
        'NYJ':'New York Jets',
        'PHI':'Philadelphia Eagles',
        'PIT':'Pittsburgh Steelers',
        'SF':'San Francisco 49ers',
        'SEA':'Seattle Seahawks',
        'TB':'Tampa Bay Buccaneers',
        'TEN':'Tennessee Titans',
        'WSH':'Washington Football Team',
        'WAS':'Washington Football Team'
    }
    
    if is_team:
        return team_mapping[game['team']]
    
    else:
        return team_mapping[game['opponent']]
    
df['team_full'] = df.apply(lambda x: fix_team_names(x, is_team=True), axis=1)
df['opponent_full'] = df.apply(lambda x: fix_team_names(x, is_team=False), axis=1)
df.head()

,season,week,team,opponent,score,opponent_score,qb,passing_value,rushing_value,pass_def_value,rush_def_value,special_teams_value,total_plays_standardized,total_possession_time_standardized,pass_percentage_standardized,team_full,opponent_full
0,2022,1,ARI,KC,21,44,K. Murray,0.022362,0.456225,-2.423499,0.149580,0.252907,-0.287243,-1.191364,0.868136,Arizona Cardinals,Kansas City Chiefs
1,2022,1,ATL,NO,26,27,M. Mariota,-0.112911,0.037099,-0.090737,-1.034817,1.055577,1.220221,0.760677,-1.040346,Atlanta Falcons,New Orleans Saints
2,2022,1,BAL,NYJ,24,9,L. Jackson,0.447970,-0.212488,0.634443,0.655233,1.591348,-1.330871,-0.682136,0.473307,Baltimore Ravens,New York Jets
3,2022,1,BUF,LA,31,10,J. Allen,1.414945,-0.550318,1.304938,0.187208,0.478257,-0.751078,0.182009,0.042220,Buffalo Bills,Los Angeles Rams
4,2022,1,CAR,CLE,24,26,B. Mayfield,-0.203192,0.703623,0.723040,-1.476490,-0.429324,-1.678748,-2.055508,0.519542,Carolina Panthers,Cleveland Browns

In [3]:
# Save raw data frame with values

# df.to_csv('data/05_value_models_combined.csv')

In [4]:
df = pd.read_csv('data/05_seasontest_value_models_combined.csv')
current_week_data = pd.read_csv('data/04_seasontest_current_week_data.csv')

In [6]:
df.tail()

,Unnamed: 0,season,week,team,opponent,score,opponent_score,qb,passing_value,rushing_value,pass_def_value,rush_def_value,special_teams_value,total_plays_standardized,total_possession_time_standardized,pass_percentage_standardized,team_full,opponent_full
562,562,2022,21,KC,CIN,23,20,P. Mahomes,0.546928,-0.846414,0.124873,-0.579377,-0.306923,0.408510,0.556214,1.091171,Kansas City Chiefs,Cincinnati Bengals
563,563,2022,21,PHI,SF,31,7,J. Hurts,-0.094271,0.749640,1.302655,2.262539,-0.640617,0.640427,1.617106,-1.705059,Philadelphia Eagles,San Francisco 49ers
564,564,2022,21,SF,PHI,7,31,J. Johnson,-0.513335,-2.333766,0.065312,-1.061473,0.640617,-2.374500,-1.824041,-0.955701,San Francisco 49ers,Philadelphia Eagles
565,565,2022,22,KC,PHI,38,35,P. Mahomes,1.474598,1.352243,-1.120473,0.173134,-0.297950,-1.214913,-1.442120,-0.398039,Kansas City Chiefs,Philadelphia Eagles
566,566,2022,22,PHI,KC,35,38,J. Hurts,1.088363,-0.039039,-1.507736,-1.182679,0.297950,0.988303,1.235185,-0.233319,Philadelphia Eagles,Kansas City Chiefs

In [8]:
home_week = current_week_data[['season', 'week', 'home', 'away', 'home_qb']]
home_week = home_week.rename(columns = {'home': 'team', 
                                       'away': 'opponent',
                                       'home_qb': 'qb'})
away_week = current_week_data[['season', 'week', 'home', 'away', 'home_qb']]
away_week = away_week.rename(columns = {'away': 'team', 
                                       'home': 'opponent',
                                       'away_qb': 'qb'})
away_week

   season  week opponent team     home_qb
0    2023     1       KC  DET  P. Mahomes

In [12]:
pd.concat([df, home_week], axis=1)

,Unnamed: 0,season,week,team,opponent,score,opponent_score,qb,passing_value,rushing_value,...,total_plays_standardized,total_possession_time_standardized,pass_percentage_standardized,team_full,opponent_full,season,week,team,opponent,qb
0,0,2022,1,ARI,KC,21,44,K. Murray,0.022362,0.456225,...,-0.287243,-1.191364,0.868136,Arizona Cardinals,Kansas City Chiefs,2023.0,1.0,KC,DET,P. Mahomes
1,1,2022,1,ATL,NO,26,27,M. Mariota,-0.112911,0.037099,...,1.220221,0.760677,-1.040346,Atlanta Falcons,New Orleans Saints,NaN,NaN,NaN,NaN,NaN
2,2,2022,1,BAL,NYJ,24,9,L. Jackson,0.447970,-0.212488,...,-1.330871,-0.682136,0.473307,Baltimore Ravens,New York Jets,NaN,NaN,NaN,NaN,NaN
3,3,2022,1,BUF,LA,31,10,J. Allen,1.414945,-0.550318,...,-0.751078,0.182009,0.042220,Buffalo Bills,Los Angeles Rams,NaN,NaN,NaN,NaN,NaN
4,4,2022,1,CAR,CLE,24,26,B. Mayfield,-0.203192,0.703623,...,-1.678748,-2.055508,0.519542,Carolina Panthers,Cleveland Browns,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
562,562,2022,21,KC,CIN,23,20,P. Mahomes,0.546928,-0.846414,...,0.408510,0.556214,1.091171,Kansas City Chiefs,Cincinnati Bengals,NaN,NaN,NaN,NaN,NaN
563,563,2022,21,PHI,SF,31,7,J. Hurts,-0.094271,0.749640,...,0.640427,1.617106,-1.705059,Philadelphia Eagles,San Francisco 49ers,NaN,NaN,NaN,NaN,NaN
564,564,2022,21,SF,PHI,7,31,J. Johnson,-0.513335,-2.333766,...,-2.374500,-1.824041,-0.955701,San Francisco 49ers,Philadelphia Eagles,NaN,NaN,NaN,NaN,NaN
565,565,2022,22,KC,PHI,38,35,P. Mahomes,1.474598,1.352243,...,-1.214913,-1.442120,-0.398039,Kansas City Chiefs,Philadelphia Eagles,NaN,NaN,NaN,NaN,NaN
566,566,2022,22,PHI,KC,35,38,J. Hurts,1.088363,-0.039039,...,0.988303,1.235185,-0.233319,Philadelphia Eagles,Kansas City Chiefs,NaN,NaN,NaN,NaN,NaN

In [42]:
# Save data frame with past 5 games rolling stats

# Weighted average approach

def weighted_avg(values):
    if len(values) == 1:
        weights = np.array([1])
    elif len(values) == 2:
        weights = np.array([.25, .75])
    elif len(values) == 3:
        weights = np.array([.1, .3, .6])
    elif len(values) == 4:
        weights = np.array([.1, .15, .25, .5])
    elif len(values) == 5:
        weights = np.array([.1, .1, .15, .15, .5])
    
    return np.sum(weights * values)

offense_base = df.copy()[['season', 'week', 'team', 'qb']]
defense_base = df.copy()[['season', 'week', 'team']]

offense_rolling = df[['team', 'qb', 'passing_value', 'rushing_value',
                     'total_plays_standardized', 'total_possession_time_standardized', 
                     'pass_percentage_standardized']]
offense_rolling = offense_rolling.groupby(by=['team', 'qb']).rolling(
    5, closed='left', min_periods=1).apply(lambda x: weighted_avg(x)).reset_index(level=['team', 'qb'], drop=True)

defense_rolling = df[['team', 'pass_def_value', 'rush_def_value', 'special_teams_value']]
defense_rolling = defense_rolling.groupby(by=['team']).rolling(
    5, closed='left', min_periods=1).apply(lambda x: weighted_avg(x)).reset_index(level=['team'], drop=True)

offense = offense_base.join(offense_rolling)
defense = defense_base.join(defense_rolling).dropna()

combined = offense.merge(defense, how='left')

In [43]:
combined

,season,week,team,qb,passing_value,rushing_value,total_plays_standardized,total_possession_time_standardized,pass_percentage_standardized,pass_def_value,rush_def_value,special_teams_value
0,2014,1,ARI,C. Palmer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2014,1,ATL,M. Ryan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2014,1,BAL,J. Flacco,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2014,1,BUF,E. Manuel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2014,1,CAR,D. Anderson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
4866,2022,21,KC,P. Mahomes,0.601189,0.460893,-0.112810,0.293756,-0.042104,0.667588,-0.924365,-0.554750
4867,2022,21,PHI,J. Hurts,0.336387,1.784683,0.571417,0.722064,-1.156340,1.071502,-0.584493,0.282612
4868,2022,21,SF,J. Johnson,NaN,NaN,NaN,NaN,NaN,0.459523,0.086384,-0.025820
4869,2022,22,KC,P. Mahomes,0.404213,-0.042373,-0.157677,0.089844,0.486147,0.561616,-0.780062,-0.348834
4870,2022,22,PHI,J. Hurts,-0.074393,1.385724,0.644326,1.049812,-1.428685,1.027831,0.814121,-0.104304

In [44]:
# NOTE: Pretty sure everything in previous code block is good, but do some checks next time i look at this

combined[combined.team=='LV'].tail(15)

,season,week,team,qb,passing_value,rushing_value,total_plays_standardized,total_possession_time_standardized,pass_percentage_standardized,pass_def_value,rush_def_value,special_teams_value
4386,2022,3,LV,D. Carr,-0.289039,0.240253,0.038617,-0.027289,0.806264,-0.013109,-0.811653,0.778108
4418,2022,4,LV,D. Carr,-0.072366,0.440675,0.201262,0.070663,1.097439,-0.866178,0.148637,0.387344
4450,2022,5,LV,D. Carr,-0.275119,0.741493,0.975223,0.740127,0.216354,-0.195409,0.581759,-0.110940
4508,2022,7,LV,D. Carr,0.167159,0.637845,-0.174502,0.033419,0.149405,-0.643835,0.064132,0.671475
4536,2022,8,LV,D. Carr,0.621373,0.933959,0.178828,0.658749,-0.277125,-0.228220,-0.188846,0.437196
4564,2022,9,LV,D. Carr,-0.468231,-0.776979,-0.454923,-0.310531,0.813593,-0.656645,-0.005825,0.536275
4591,2022,10,LV,D. Carr,0.254681,-0.433269,-0.438098,-0.205502,0.439543,-0.824652,0.040282,0.592378
4620,2022,11,LV,D. Carr,0.065582,-0.781660,-0.466140,-0.134366,0.492800,-0.458321,-0.840738,1.073924
4649,2022,12,LV,D. Carr,0.295305,-0.329531,-0.253020,0.163960,0.402571,-0.319527,-0.189754,0.637303
4679,2022,13,LV,D. Carr,0.488269,-0.183098,0.571417,0.733051,-0.168349,-0.505156,0.245931,-0.010756
4707,2022,14,LV,D. Carr,-0.158723,0.268598,-0.079159,0.155394,-0.391962,0.027123,0.028800,0.448950
4737,2022,15,LV,D. Carr,-0.042790,0.375619,-0.124027,0.276251,-1.363946,-0.062324,0.741554,0.367414
4769,2022,16,LV,D. Carr,-0.221285,0.360137,-0.039900,0.507165,-0.300723,0.488679,0.010537,0.391560
4799,2022,17,LV,J. Stidham,NaN,NaN,NaN,NaN,NaN,0.123155,0.376274,0.672824
4831,2022,18,LV,J. Stidham,0.433121,-0.045708,0.234912,0.373272,-0.702300,-0.100750,-0.993759,0.681719

In [45]:
df[df.team == 'LV'].tail(15)

,season,week,team,opponent,score,opponent_score,qb,passing_value,rushing_value,pass_def_value,rush_def_value,special_teams_value,total_plays_standardized,total_possession_time_standardized,pass_percentage_standardized,team_full,opponent_full
4386,2022,3,LV,TEN,22,24,D. Carr,0.246131,0.561686,-1.252657,0.235539,-0.218493,0.234912,0.093941,1.158906,Las Vegas Raiders,Tennessee Titans
4418,2022,4,LV,DEN,32,23,D. Carr,-0.389152,1.057473,0.216146,1.344218,-0.504775,1.917436,1.714062,-0.845470,Las Vegas Raiders,Denver Broncos
4450,2022,5,LV,KC,29,30,D. Carr,0.558517,0.784474,-0.846055,-0.236504,1.170337,-0.774603,-0.323194,-0.265256,Las Vegas Raiders,Kansas City Chiefs
4508,2022,7,LV,HOU,38,20,D. Carr,1.218571,1.203649,-0.129459,-0.324343,0.578142,0.010575,0.905864,-0.578040,Las Vegas Raiders,Houston Texans
4536,2022,8,LV,NO,0,24,D. Carr,-1.440984,-2.474226,-0.813333,-0.159348,0.692660,-1.111108,-1.157463,1.817487,Las Vegas Raiders,New Orleans Saints
4564,2022,9,LV,JAX,20,27,D. Carr,0.542212,-0.853754,-1.240484,0.004129,0.670404,-0.774603,-0.613698,0.729397,Las Vegas Raiders,Jacksonville Jaguars
4591,2022,10,LV,IND,20,25,D. Carr,0.045378,-0.962550,-0.105394,-1.522742,1.389234,-0.213761,0.146083,0.390195,Las Vegas Raiders,Indianapolis Colts
4620,2022,11,LV,DEN,22,16,D. Carr,0.458815,0.139945,-0.046733,0.172814,0.402555,0.010575,0.518524,0.221375,Las Vegas Raiders,Denver Broncos
4649,2022,12,LV,SEA,40,34,D. Carr,1.005034,0.546181,-0.553910,0.927884,-0.831662,1.580932,1.620952,-1.029545,Las Vegas Raiders,Seattle Seahawks
4679,2022,13,LV,LAC,27,20,D. Carr,-0.874118,0.694619,0.503614,0.031113,0.614703,-0.438098,-0.237532,-0.765392,Las Vegas Raiders,Los Angeles Chargers
4707,2022,14,LV,LA,16,17,D. Carr,-0.225692,0.543519,-0.079134,1.465395,0.441557,-0.550266,0.004555,-2.311726,Las Vegas Raiders,Los Angeles Rams
4737,2022,15,LV,NE,30,24,D. Carr,-0.405397,0.211607,0.970142,-0.648017,0.552064,-0.101593,0.656328,0.483324,Las Vegas Raiders,New England Patriots
4769,2022,16,LV,PIT,10,13,D. Carr,-0.616708,-0.672422,-0.010933,0.315534,1.090953,-1.447612,-0.665840,0.426538,Las Vegas Raiders,Pittsburgh Steelers
4799,2022,17,LV,SF,34,37,J. Stidham,0.433121,-0.045708,-0.574159,-2.187076,0.659282,0.234912,0.373272,-0.702300,Las Vegas Raiders,San Francisco 49ers
4831,2022,18,LV,KC,13,31,J. Stidham,-0.874341,0.054613,-0.021967,-2.674979,0.129630,0.347080,0.868620,0.353309,Las Vegas Raiders,Kansas City Chiefs

In [46]:
# fix team names

combined['team_full'] = combined.apply(lambda x: fix_team_names(x, is_team=True), axis=1)
# combined['opponent_full'] = combined.apply(lambda x: fix_team_names(x, is_team=False), axis=1)
combined.head()

,season,week,team,qb,passing_value,rushing_value,total_plays_standardized,total_possession_time_standardized,pass_percentage_standardized,pass_def_value,rush_def_value,special_teams_value,team_full
0,2014,1,ARI,C. Palmer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Arizona Cardinals
1,2014,1,ATL,M. Ryan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Atlanta Falcons
2,2014,1,BAL,J. Flacco,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Baltimore Ravens
3,2014,1,BUF,E. Manuel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Buffalo Bills
4,2014,1,CAR,D. Anderson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Carolina Panthers

In [48]:
# Save aggregated data frame with values

combined.to_csv('data/05_value_models_aggregated.csv')

In [49]:
combined[(combined.team == 'BAL') & (combined.season==2022)]

,season,week,team,qb,passing_value,rushing_value,total_plays_standardized,total_possession_time_standardized,pass_percentage_standardized,pass_def_value,rush_def_value,special_teams_value,team_full
4306,2022,1,BAL,L. Jackson,-0.415754,0.485301,0.975223,1.349442,0.163035,-0.561149,0.493865,0.506075,Baltimore Ravens
4338,2022,2,BAL,L. Jackson,-0.137177,0.193148,0.004967,0.501020,0.058586,-0.104427,0.357672,1.035229,Baltimore Ravens
4370,2022,3,BAL,L. Jackson,0.681141,-0.124710,-0.499790,-0.275894,-0.163475,-0.906975,-0.275513,0.958328,Baltimore Ravens
4402,2022,4,BAL,L. Jackson,0.218432,1.283315,-0.499790,0.052414,-0.093808,0.061227,-0.458992,0.878303,Baltimore Ravens
4434,2022,5,BAL,L. Jackson,-0.216507,0.983557,-0.353972,0.787986,-0.448500,-0.135005,-0.170218,0.576509,Baltimore Ravens
4466,2022,6,BAL,L. Jackson,-0.260497,0.913281,-0.404447,0.055579,-0.338509,0.320536,-0.601620,1.140967,Baltimore Ravens
4494,2022,7,BAL,L. Jackson,-0.200016,1.505811,-0.477357,-0.102522,-0.259192,-0.528033,-0.176052,-0.017267,Baltimore Ravens
4522,2022,8,BAL,L. Jackson,-0.673509,0.912814,-0.157677,0.513496,-1.489984,0.013299,-0.650980,1.002998,Baltimore Ravens
4551,2022,9,BAL,L. Jackson,-0.349834,1.362202,0.532158,1.118900,-0.658421,-0.227432,-0.164781,0.902648,Baltimore Ravens
4605,2022,11,BAL,L. Jackson,0.020695,1.035226,0.184436,1.171228,-1.446409,0.164520,0.101168,0.712932,Baltimore Ravens
4633,2022,12,BAL,L. Jackson,-0.338241,0.566294,0.268562,0.878676,-0.766208,0.804131,0.301297,0.098064,Baltimore Ravens
4664,2022,13,BAL,T. Huntley,-0.903672,0.588670,0.818187,0.314799,-0.459973,-0.226250,1.100445,0.150370,Baltimore Ravens
4694,2022,14,BAL,T. Huntley,-0.405933,0.560989,0.610676,0.308840,-0.129478,0.113002,1.090537,0.017128,Baltimore Ravens
4721,2022,15,BAL,T. Huntley,-0.118231,0.676406,0.218087,0.475507,-1.376789,-0.023500,0.675097,0.584930,Baltimore Ravens
4753,2022,16,BAL,T. Huntley,-1.055927,0.660167,0.122744,-0.096004,-0.748505,0.239210,-0.071832,0.124101,Baltimore Ravens
4785,2022,17,BAL,T. Huntley,-0.493282,0.521435,-0.550266,-0.300289,-1.670043,0.046439,0.893889,-0.075770,Baltimore Ravens
4815,2022,18,BAL,A. Brown,NaN,NaN,NaN,NaN,NaN,-0.104945,-0.502998,0.616377,Baltimore Ravens
4845,2022,19,BAL,T. Huntley,0.008815,0.046649,-0.970897,-0.621147,-1.415910,0.334822,0.259330,0.308205,Baltimore Ravens

In [50]:
df[df.team == 'SF'].tail(15)

,season,week,team,opponent,score,opponent_score,qb,passing_value,rushing_value,pass_def_value,rush_def_value,special_teams_value,total_plays_standardized,total_possession_time_standardized,pass_percentage_standardized,team_full,opponent_full
4489,2022,6,SF,ATL,14,28,J. Garoppolo,0.150830,-2.791287,-1.014961,-0.508785,0.131760,-0.998939,-0.837163,1.226723,San Francisco 49ers,Atlanta Falcons
4516,2022,7,SF,KC,23,44,J. Garoppolo,0.087143,0.580775,-2.218665,-1.196759,1.248613,1.020090,0.764336,1.217384,San Francisco 49ers,Kansas City Chiefs
4546,2022,8,SF,LA,31,14,J. Garoppolo,1.600826,0.151594,0.054764,0.743690,0.408923,-1.447612,-0.088555,-0.300324,San Francisco 49ers,Los Angeles Rams
4599,2022,10,SF,LAC,22,16,J. Garoppolo,0.369584,0.220537,0.736455,-0.106955,-0.568912,0.795753,1.486873,-1.598667,San Francisco 49ers,Los Angeles Chargers
4628,2022,11,SF,ARI,38,10,J. Garoppolo,1.536268,1.026531,0.550368,0.747276,0.188465,-0.886771,-0.263603,-0.587765,San Francisco 49ers,Arizona Cardinals
4659,2022,12,SF,NO,13,0,J. Garoppolo,-0.001005,-0.190469,0.640552,1.454999,1.070847,0.347080,1.006423,-0.045922,San Francisco 49ers,New Orleans Saints
4689,2022,13,SF,MIA,33,17,B. Purdy,-0.053421,-0.126492,1.348306,-0.111838,0.470714,2.029605,2.324866,0.024851,San Francisco 49ers,Miami Dolphins
4716,2022,14,SF,TB,35,7,B. Purdy,1.089423,0.527490,0.606800,0.483648,1.237796,-0.774603,0.522249,-1.822974,San Francisco 49ers,Tampa Bay Buccaneers
4747,2022,15,SF,SEA,21,13,B. Purdy,0.651377,1.057992,1.113096,-0.261235,-2.123656,-0.438098,0.600462,-1.171305,San Francisco 49ers,Seattle Seahawks
4779,2022,16,SF,WAS,37,20,B. Purdy,0.791740,0.146685,-0.484144,2.863790,1.415588,-1.335444,-0.874407,-0.938109,San Francisco 49ers,Washington Football Team
4809,2022,17,SF,LV,37,34,B. Purdy,0.552776,2.237359,-0.452415,0.206605,-0.659282,0.010575,0.175878,-0.058037,San Francisco 49ers,Las Vegas Raiders
4841,2022,18,SF,ARI,38,13,B. Purdy,0.771077,-0.094765,1.819759,0.196554,0.633354,-0.438098,0.872344,-1.852352,San Francisco 49ers,Arizona Cardinals
4855,2022,19,SF,SEA,41,23,B. Purdy,2.023435,0.681747,-0.139021,-0.472432,0.568763,0.234912,0.544595,-0.845470,San Francisco 49ers,Seattle Seahawks
4864,2022,20,SF,DAL,19,12,B. Purdy,0.259976,-0.198592,0.602136,-0.358547,-0.563537,0.122744,0.570666,-0.920464,San Francisco 49ers,Dallas Cowboys
4868,2022,21,SF,PHI,7,31,J. Johnson,-0.560147,-2.345301,0.172187,-1.337421,0.597381,-2.344959,-1.734748,-1.160443,San Francisco 49ers,Philadelphia Eagles

In [51]:
offense_base[offense_base.team == 'SF']

      season  week team             qb
28      2014     1   SF  C. Kaepernick
60      2014     2   SF  C. Kaepernick
92      2014     3   SF  C. Kaepernick
118     2014     4   SF  C. Kaepernick
148     2014     5   SF  C. Kaepernick
...      ...   ...  ...            ...
4809    2022    17   SF       B. Purdy
4841    2022    18   SF       B. Purdy
4855    2022    19   SF       B. Purdy
4864    2022    20   SF       B. Purdy
4868    2022    21   SF     J. Johnson

[153 rows x 4 columns]

In [52]:
defense

      season  week team  pass_def_value  rush_def_value  special_teams_value
32      2014     2  ARI        0.027688        1.468394            -0.996743
33      2014     2  ATL       -0.559094       -1.005162            -0.243872
34      2014     2  BAL       -0.765953        0.727127            -0.442100
35      2014     2  BUF        0.504718       -0.187514             0.780553
36      2014     2  CAR        0.982581       -0.392165            -0.725290
...      ...   ...  ...             ...             ...                  ...
4866    2022    21   KC        0.667588       -0.924365            -0.554750
4867    2022    21  PHI        1.071502       -0.584493             0.282612
4868    2022    21   SF        0.459523        0.086384            -0.025820
4869    2022    22   KC        0.561616       -0.780062            -0.348834
4870    2022    22  PHI        1.027831        0.814121            -0.104304

[4839 rows x 6 columns]