In [2]:
# Import packages

import pandas as pd 
import numpy as np 
import os

In [2]:
# Import data

rb = pd.read_csv('data/04_seasontest_initial_rushing_values.csv')
rb = rb.drop(columns = ['Unnamed: 0'])
pass_def = pd.read_csv('data/04_seasontest_initial_pass_defense_values.csv')
pass_def = pass_def.drop(columns = ['Unnamed: 0'])
rush_def = pd.read_csv('data/04_seasontest_initial_rush_defense_values.csv')
rush_def = rush_def.drop(columns = ['Unnamed: 0'])
qb = pd.read_csv('data/04_seasontest_initial_qb_values.csv')
qb = qb.drop(columns = ['Unnamed: 0'])
qb = qb.drop(columns = ['Unnamed: 0.1'])
st = pd.read_csv('data/04_seasontest_initial_st_values.csv')
st = st.drop(columns = ['Unnamed: 0'])
extra = pd.read_csv('data/04_seasontest_initial_extra_values.csv')
extra = extra.drop(columns = ['Unnamed: 0'])

In [3]:
extra

,season,week,team,opponent,score,opponent_score,total_plays,total_possession_time_seconds,pass_percentage,run_percentage,total_plays_standardized,total_possession_time_standardized,pass_percentage_standardized
0,2022,1,ARI,KC,21,44,63.0,1518.0,0.671875,0.328125,-0.287243,-1.191364,0.868136
1,2022,1,ATL,NO,26,27,76.0,2024.0,0.457143,0.542857,1.220221,0.760677,-1.040346
2,2022,1,BAL,NYJ,24,9,54.0,1650.0,0.627451,0.372549,-1.330871,-0.682136,0.473307
3,2022,1,BUF,LA,31,10,59.0,1874.0,0.578947,0.421053,-0.751078,0.182009,0.042220
4,2022,1,CAR,CLE,24,26,51.0,1294.0,0.632653,0.367347,-1.678748,-2.055508,0.519542
...,...,...,...,...,...,...,...,...,...,...,...,...,...
563,2022,21,KC,CIN,23,20,69.0,1971.0,0.696970,0.303030,0.408510,0.556214,1.091171
564,2022,21,PHI,SF,31,7,71.0,2246.0,0.382353,0.617647,0.640427,1.617106,-1.705059
565,2022,21,SF,PHI,7,31,45.0,1354.0,0.466667,0.533333,-2.374500,-1.824041,-0.955701
566,2022,22,KC,PHI,38,35,55.0,1453.0,0.529412,0.470588,-1.214913,-1.442120,-0.398039
567,2022,22,PHI,KC,35,38,74.0,2147.0,0.547945,0.452055,0.988303,1.235185,-0.233319

In [4]:
# Put data into one data frame that just has the game identifiers and value numbers

# qb = qb.copy()[['season', 'week', 'team', 'opponent', 'score', 'opponent_score', 'qb', 'qb_value', 'passing_value']]
qb = qb.copy()[['season', 'week', 'team', 'opponent', 'score', 'opponent_score', 'qb', 'passing_value']]
rb = rb.copy()[['season', 'week', 'team', 'opponent', 'score', 'opponent_score', 'rushing_value']]
pass_def = pass_def.copy()[['season', 'week', 'team', 'opponent', 'score', 'opponent_score', 'pass_def_value']]
rush_def = rush_def.copy()[['season', 'week', 'team', 'opponent', 'score', 'opponent_score', 'rush_def_value']]
st = st.copy()[['season', 'week', 'team', 'opponent', 'score', 'opponent_score', 'special_teams_value']]
extra = extra.copy()[['season', 'week', 'team', 'opponent', 'score', 'opponent_score', 'total_plays_standardized', 'total_possession_time_standardized', 'pass_percentage_standardized']]
df = qb.copy()
df = df.merge(rb).merge(pass_def).merge(rush_def).merge(st).merge(extra)
df = df.drop_duplicates()
df.head()

,season,week,team,opponent,score,opponent_score,qb,passing_value,rushing_value,pass_def_value,rush_def_value,special_teams_value,total_plays_standardized,total_possession_time_standardized,pass_percentage_standardized
0,2022,1,ARI,KC,21,44,K. Murray,0.022362,0.456225,-2.423499,0.149580,0.252907,-0.287243,-1.191364,0.868136
1,2022,1,ATL,NO,26,27,M. Mariota,-0.112911,0.037099,-0.090737,-1.034817,1.055577,1.220221,0.760677,-1.040346
2,2022,1,BAL,NYJ,24,9,L. Jackson,0.447970,-0.212488,0.634443,0.655233,1.591348,-1.330871,-0.682136,0.473307
3,2022,1,BUF,LA,31,10,J. Allen,1.414945,-0.550318,1.304938,0.187208,0.478257,-0.751078,0.182009,0.042220
4,2022,1,CAR,CLE,24,26,B. Mayfield,-0.203192,0.703623,0.723040,-1.476490,-0.429324,-1.678748,-2.055508,0.519542

In [21]:
# Manual Input of current week games

# UPDATE THIS before each run

current_week = 1
current_season = 2023

qbs = pd.read_csv('data/03_seasontest_team_primary_qb_lookup_table.csv')

# Fix team names

# Move to helper functions

def fix_team_names(team_abrv):
    team_mapping = {
        'ARI':'Arizona Cardinals',
        'ATL':'Atlanta Falcons',
        'BAL':'Baltimore Ravens',
        'BUF':'Buffalo Bills',
        'CAR':'Carolina Panthers',
        'CHI':'Chicago Bears',
        'CIN':'Cincinnati Bengals',
        'CLE':'Cleveland Browns',
        'DAL':'Dallas Cowboys',
        'DEN':'Denver Broncos',
        'DET':'Detroit Lions',
        'GB':'Green Bay Packers',
        'HOU':'Houston Texans',
        'IND':'Indianapolis Colts',
        'JAX':'Jacksonville Jaguars',
        'KC':'Kansas City Chiefs',
        'OAK':'Las Vegas Raiders',
        'LV':'Las Vegas Raiders',
        'LAC':'Los Angeles Chargers',
        'LAR':'Los Angeles Rams',
        'LA':'Los Angeles Rams',
        'MIA':'Miami Dolphins',
        'MIN':'Minnesota Vikings',
        'NE':'New England Patriots',
        'NO':'New Orleans Saints',
        'NYG':'New York Giants',
        'NYJ':'New York Jets',
        'PHI':'Philadelphia Eagles',
        'PIT':'Pittsburgh Steelers',
        'SF':'San Francisco 49ers',
        'SEA':'Seattle Seahawks',
        'TB':'Tampa Bay Buccaneers',
        'TEN':'Tennessee Titans',
        'WSH':'Washington Football Team',
        'WAS':'Washington Football Team'
    }

    return team_mapping[team_abrv]

    
qbs['team_full'] = qbs.apply(lambda x: fix_team_names(x.team), axis=1)

if current_week == 1:
    check_week = 18
    check_season = current_season-1
    
else:
    check_week = current_week - 1
    check_season = current_season

current_week_qbs = qbs[(qbs.season == check_season) & (qbs.week == check_week)]
current_week_qbs = current_week_qbs[['season', 'week', 'team', 'team_full', 'qb']]
current_week_qbs['week'] = current_week
current_week_qbs['season'] = current_season

qb_dict = {game['team_full']:game['qb'] for index, game in current_week_qbs.iterrows()}

# QB Updates, if necessary

# qb_dict['Arizona Cardinals'] = 'Kyler Murray'
# qb_dict['Atlanta Falcons'] = 'Marcus Mariota'
# qb_dict['Baltimore Ravens'] = 'Lamar Jackson'
# qb_dict['Buffalo Bills'] = 'Josh Allen'
# qb_dict['Carolina Panthers'] = 'P.J. Walker'
# qb_dict['Chicago Bears'] = 'Trevor Siemian'
# qb_dict['Cincinnati Bengals'] = 'Joe Burrow'
# qb_dict['Cleveland Browns'] = 'Jacoby Brissett'
# qb_dict['Dallas Cowboys'] = 'Dak Prescott'
# qb_dict['Denver Broncos'] = 'Russell Wilson'
# qb_dict['Detroit Lions'] = 'Jared Goff'
# qb_dict['Green Bay Packers'] = 'Aaron Rodgers'
# qb_dict['Houston Texans'] = 'Kyle Allen'
# qb_dict['Indianapolis Colts'] = 'Matt Ryan'
# qb_dict['Jacksonville Jaguars'] = 'Trevor Lawrence'
# qb_dict['Kansas City Chiefs'] = 'Patrick Mahomes'
# qb_dict['Las Vegas Raiders'] = 'Derek Carr'
# qb_dict['Los Angeles Chargers'] = 'Justin Herbert'
# qb_dict['Los Angeles Rams'] = 'Matthew Stafford'
# qb_dict['Miami Dolphins'] = 'Tua Tagovailoa'
# qb_dict['Minnesota Vikings'] = 'Kirk Cousins'
# qb_dict['New England Patriots'] = 'Mac Jones'
# qb_dict['New Orleans Saints'] = 'Andy Dalton'
# qb_dict['New York Giants'] = 'Daniel Jones'
# qb_dict['New York Jets'] = 'Mike White'
# qb_dict['Philadelphia Eagles'] = 'Jalen Hurts'
# qb_dict['Pittsburgh Steelers'] = 'Kenny Pickett'
# qb_dict['San Francisco 49ers'] = 'Jimmy Garoppolo'
# qb_dict['Seattle Seahawks'] = 'Geno Smith'
# qb_dict['Tampa Bay Buccaneers'] = 'Tom Brady'
# qb_dict['Tennessee Titans'] = 'Ryan Tannehill'
# qb_dict['Washington Football Team'] = 'Taylor Heinicke'

# CHECK: Are qbs correct?

# IF NOT, update in previous step. Otherwise, good to go

# for team, qb in qb_dict.items():
#     print('{}: {}'.format(team, qb))
#     print()

# Manually Inputted
# While not ideal, manually inputting the odds/games in doesn't take too much time/effort
# In the future, want to create a web scraping bot to automate getting the necessary odds and game data
# For now, this will have to do

# Column Order
# 'season', 'week', 'away', 'home', 'away_moneyline', 'home_moneyline', 'away_spread', 'over_under'

manual_input = {
    '{}{}{}'.format(current_season, current_week, 1): [current_season, current_week, 'DET','KC',
                                                      -225, 185, 4.5, 52.5]
#     '{}{}{}'.format(current_season, current_week, 2): [current_season, current_week, 'NYG','DAL',
#                                                       350, -435, 10, -10, 45.5],
#     '{}{}{}'.format(current_season, current_week, 3): [current_season, current_week, 'NE','MIN',
#                                                       115, -135, 2.5, -2.5, 42.5],
#     '{}{}{}'.format(current_season, current_week, 4): [current_season, current_week, 'HOU','MIA',
#                                                       550, -750, 13.5, -13.5, 47],
#     '{}{}{}'.format(current_season, current_week, 5): [current_season, current_week, 'BAL','JAX',
#                                                       -195, 165, -3.5, 3.5, 43.5],
#     '{}{}{}'.format(current_season, current_week, 6): [current_season, current_week, 'CHI','NYJ',
#                                                       215, -255, 6, -6, 38.5],
#     '{}{}{}'.format(current_season, current_week, 7): [current_season, current_week, 'CIN','TEN',
#                                                       -150, 130, -2.5, 2.5, 42.5],
#     '{}{}{}'.format(current_season, current_week, 8): [current_season, current_week, 'ATL','WAS',
#                                                       170, -200, 4.5, -4.5, 40.5],
#     '{}{}{}'.format(current_season, current_week, 9): [current_season, current_week, 'DEN','CAR',
#                                                       -130, 110, -1.5, 1.5, 36],
#     '{}{}{}'.format(current_season, current_week, 10): [current_season, current_week, 'TB','CLE',
#                                                       -180, 155, -3.5, 3.5, 42],
#     '{}{}{}'.format(current_season, current_week, 11): [current_season, current_week, 'LV','SEA',
#                                                       165, -195, 3.5, -3.5, 48],
#     '{}{}{}'.format(current_season, current_week, 12): [current_season, current_week, 'LAC','ARI',
#                                                       -175, 150, -3, 3, 48],
#     '{}{}{}'.format(current_season, current_week, 13): [current_season, current_week, 'LAR','KC',
#                                                       750, -1150, 15.5, -15.5, 42],
#     '{}{}{}'.format(current_season, current_week, 14): [current_season, current_week, 'NO','SF',
#                                                       330, -410, 9.5, -9.5, 43.5],
#     '{}{}{}'.format(current_season, current_week, 15): [current_season, current_week, 'GB','PHI',
#                                                       245, -295, 6.5, -6.5, 43.5]
#     '{}{}{}'.format(current_season, current_week, 16): [current_season, current_week, 'LV','KC',
#                                                       265, -320, 7, -7, 51.5]
}

manual_input

current_week_data = pd.DataFrame.from_dict(manual_input, orient='index',
                                          columns = ['season', 'week', 'away', 'home', 
                                                    'away_moneyline', 'home_moneyline', 
                                                    'away_spread', 'over_under'])
current_week_data['home_full_name'] = current_week_data.apply(lambda x: fix_team_names(x.home), axis=1)
current_week_data['away_full_name'] = current_week_data.apply(lambda x: fix_team_names(x.away), axis=1)
current_week_data['home_qb'] = current_week_data.apply(lambda x: qb_dict[x.home_full_name], axis=1)
current_week_data['away_qb'] = current_week_data.apply(lambda x: qb_dict[x.away_full_name], axis=1)

current_week_data

,season,week,away,home,away_moneyline,home_moneyline,away_spread,over_under,home_full_name,away_full_name,home_qb,away_qb
202311,2023,1,DET,KC,-225,185,4.5,52.5,Kansas City Chiefs,Detroit Lions,P. Mahomes,J. Goff

In [5]:
# Fix team names

# Move to helper functions

def fix_team_names(game, is_team=True):
    team_mapping = {
        'ARI':'Arizona Cardinals',
        'ATL':'Atlanta Falcons',
        'BAL':'Baltimore Ravens',
        'BUF':'Buffalo Bills',
        'CAR':'Carolina Panthers',
        'CHI':'Chicago Bears',
        'CIN':'Cincinnati Bengals',
        'CLE':'Cleveland Browns',
        'DAL':'Dallas Cowboys',
        'DEN':'Denver Broncos',
        'DET':'Detroit Lions',
        'GB':'Green Bay Packers',
        'HOU':'Houston Texans',
        'IND':'Indianapolis Colts',
        'JAX':'Jacksonville Jaguars',
        'KC':'Kansas City Chiefs',
        'OAK':'Las Vegas Raiders',
        'LV':'Las Vegas Raiders',
        'LAC':'Los Angeles Chargers',
        'LAR':'Los Angeles Rams',
        'LA':'Los Angeles Rams',
        'MIA':'Miami Dolphins',
        'MIN':'Minnesota Vikings',
        'NE':'New England Patriots',
        'NO':'New Orleans Saints',
        'NYG':'New York Giants',
        'NYJ':'New York Jets',
        'PHI':'Philadelphia Eagles',
        'PIT':'Pittsburgh Steelers',
        'SF':'San Francisco 49ers',
        'SEA':'Seattle Seahawks',
        'TB':'Tampa Bay Buccaneers',
        'TEN':'Tennessee Titans',
        'WSH':'Washington Football Team',
        'WAS':'Washington Football Team'
    }
    
    if is_team:
        return team_mapping[game['team']]
    
    else:
        return team_mapping[game['opponent']]
    
df['team_full'] = df.apply(lambda x: fix_team_names(x, is_team=True), axis=1)
df['opponent_full'] = df.apply(lambda x: fix_team_names(x, is_team=False), axis=1)
df.head()

,season,week,team,opponent,score,opponent_score,qb,passing_value,rushing_value,pass_def_value,rush_def_value,special_teams_value,total_plays_standardized,total_possession_time_standardized,pass_percentage_standardized,team_full,opponent_full
0,2022,1,ARI,KC,21,44,K. Murray,0.022362,0.456225,-2.423499,0.149580,0.252907,-0.287243,-1.191364,0.868136,Arizona Cardinals,Kansas City Chiefs
1,2022,1,ATL,NO,26,27,M. Mariota,-0.112911,0.037099,-0.090737,-1.034817,1.055577,1.220221,0.760677,-1.040346,Atlanta Falcons,New Orleans Saints
2,2022,1,BAL,NYJ,24,9,L. Jackson,0.447970,-0.212488,0.634443,0.655233,1.591348,-1.330871,-0.682136,0.473307,Baltimore Ravens,New York Jets
3,2022,1,BUF,LA,31,10,J. Allen,1.414945,-0.550318,1.304938,0.187208,0.478257,-0.751078,0.182009,0.042220,Buffalo Bills,Los Angeles Rams
4,2022,1,CAR,CLE,24,26,B. Mayfield,-0.203192,0.703623,0.723040,-1.476490,-0.429324,-1.678748,-2.055508,0.519542,Carolina Panthers,Cleveland Browns

In [3]:
# Save raw data frame with values

# df.to_csv('data/05_value_models_combined.csv')

In [31]:
df = pd.read_csv('data/05_seasontest_value_models_combined.csv')
df2 = pd.read_csv('data/05_seasontest_value_models_combined.csv')
current_week_data = pd.read_csv('data/04_seasontest_current_week_data.csv')

In [32]:
df.tail()

,Unnamed: 0,season,week,team,opponent,score,opponent_score,qb,passing_value,rushing_value,pass_def_value,rush_def_value,special_teams_value,total_plays_standardized,total_possession_time_standardized,pass_percentage_standardized,team_full,opponent_full
562,562,2022,21,KC,CIN,23,20,P. Mahomes,0.546928,-0.846414,0.124873,-0.579377,-0.306923,0.408510,0.556214,1.091171,Kansas City Chiefs,Cincinnati Bengals
563,563,2022,21,PHI,SF,31,7,J. Hurts,-0.094271,0.749640,1.302655,2.262539,-0.640617,0.640427,1.617106,-1.705059,Philadelphia Eagles,San Francisco 49ers
564,564,2022,21,SF,PHI,7,31,J. Johnson,-0.513335,-2.333766,0.065312,-1.061473,0.640617,-2.374500,-1.824041,-0.955701,San Francisco 49ers,Philadelphia Eagles
565,565,2022,22,KC,PHI,38,35,P. Mahomes,1.474598,1.352243,-1.120473,0.173134,-0.297950,-1.214913,-1.442120,-0.398039,Kansas City Chiefs,Philadelphia Eagles
566,566,2022,22,PHI,KC,35,38,J. Hurts,1.088363,-0.039039,-1.507736,-1.182679,0.297950,0.988303,1.235185,-0.233319,Philadelphia Eagles,Kansas City Chiefs

In [39]:
current_week_data

,Unnamed: 0,season,week,away,home,away_moneyline,home_moneyline,away_spread,over_under,home_full_name,away_full_name,home_qb,away_qb
0,202311,2023,1,DET,KC,-225,185,4.5,52.5,Kansas City Chiefs,Detroit Lions,P. Mahomes,J. Goff

In [43]:
home_week = current_week_data[['season', 'week', 'home', 'away', 'home_qb','home_full_name', 'away_full_name']]
home_week = home_week.rename(columns = {'home': 'team', 
                                       'away': 'opponent',
                                       'home_qb': 'qb',
                                       'home_full_name':'team_full',
                                       'away_full_name': 'opponent_full'})
away_week = current_week_data[['season', 'week', 'home', 'away', 'away_qb','home_full_name', 'away_full_name']]
away_week = away_week.rename(columns = {'away': 'team', 
                                       'home': 'opponent',
                                       'away_qb': 'qb',
                                       'home_full_name':'opponent_full',
                                       'away_full_name': 'team_full'})
away_week

   season  week opponent team       qb       opponent_full      team_full
0    2023     1       KC  DET  J. Goff  Kansas City Chiefs  Detroit Lions

In [44]:
df = pd.concat([df2, home_week, away_week], axis=0).reset_index()
df

,index,Unnamed: 0,season,week,team,opponent,score,opponent_score,qb,passing_value,rushing_value,pass_def_value,rush_def_value,special_teams_value,total_plays_standardized,total_possession_time_standardized,pass_percentage_standardized,team_full,opponent_full
0,0,0.0,2022,1,ARI,KC,21.0,44.0,K. Murray,0.022362,0.456225,-2.423499,0.149580,0.252907,-0.287243,-1.191364,0.868136,Arizona Cardinals,Kansas City Chiefs
1,1,1.0,2022,1,ATL,NO,26.0,27.0,M. Mariota,-0.112911,0.037099,-0.090737,-1.034817,1.055577,1.220221,0.760677,-1.040346,Atlanta Falcons,New Orleans Saints
2,2,2.0,2022,1,BAL,NYJ,24.0,9.0,L. Jackson,0.447970,-0.212488,0.634443,0.655233,1.591348,-1.330871,-0.682136,0.473307,Baltimore Ravens,New York Jets
3,3,3.0,2022,1,BUF,LA,31.0,10.0,J. Allen,1.414945,-0.550318,1.304938,0.187208,0.478257,-0.751078,0.182009,0.042220,Buffalo Bills,Los Angeles Rams
4,4,4.0,2022,1,CAR,CLE,24.0,26.0,B. Mayfield,-0.203192,0.703623,0.723040,-1.476490,-0.429324,-1.678748,-2.055508,0.519542,Carolina Panthers,Cleveland Browns
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,564,564.0,2022,21,SF,PHI,7.0,31.0,J. Johnson,-0.513335,-2.333766,0.065312,-1.061473,0.640617,-2.374500,-1.824041,-0.955701,San Francisco 49ers,Philadelphia Eagles
565,565,565.0,2022,22,KC,PHI,38.0,35.0,P. Mahomes,1.474598,1.352243,-1.120473,0.173134,-0.297950,-1.214913,-1.442120,-0.398039,Kansas City Chiefs,Philadelphia Eagles
566,566,566.0,2022,22,PHI,KC,35.0,38.0,J. Hurts,1.088363,-0.039039,-1.507736,-1.182679,0.297950,0.988303,1.235185,-0.233319,Philadelphia Eagles,Kansas City Chiefs
567,0,NaN,2023,1,KC,DET,NaN,NaN,P. Mahomes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kansas City Chiefs,Detroit Lions
568,0,NaN,2023,1,DET,KC,NaN,NaN,J. Goff,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Detroit Lions,Kansas City Chiefs

In [45]:
# Save data frame with past 5 games rolling stats

# Weighted average approach

def weighted_avg(values):
    if len(values) == 1:
        weights = np.array([1])
    elif len(values) == 2:
        weights = np.array([.25, .75])
    elif len(values) == 3:
        weights = np.array([.1, .3, .6])
    elif len(values) == 4:
        weights = np.array([.1, .15, .25, .5])
    elif len(values) == 5:
        weights = np.array([.1, .1, .15, .15, .5])
    
    return np.sum(weights * values)

offense_base = df.copy()[['season', 'week', 'team', 'qb']]
defense_base = df.copy()[['season', 'week', 'team']]

offense_rolling = df[['team', 'qb', 'passing_value', 'rushing_value',
                     'total_plays_standardized', 'total_possession_time_standardized', 
                     'pass_percentage_standardized']]
offense_rolling = offense_rolling.groupby(by=['team', 'qb']).rolling(
    5, closed='left', min_periods=1).apply(lambda x: weighted_avg(x)).reset_index(level=['team', 'qb'], drop=True)

defense_rolling = df[['team', 'pass_def_value', 'rush_def_value', 'special_teams_value']]
defense_rolling = defense_rolling.groupby(by=['team']).rolling(
    5, closed='left', min_periods=1).apply(lambda x: weighted_avg(x)).reset_index(level=['team'], drop=True)

offense = offense_base.join(offense_rolling)
defense = defense_base.join(defense_rolling).dropna()

combined = offense.merge(defense, how='left')

In [46]:
combined

,season,week,team,qb,passing_value,rushing_value,total_plays_standardized,total_possession_time_standardized,pass_percentage_standardized,pass_def_value,rush_def_value,special_teams_value
0,2022,1,ARI,K. Murray,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022,1,ATL,M. Mariota,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022,1,BAL,L. Jackson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022,1,BUF,J. Allen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2022,1,CAR,B. Mayfield,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
564,2022,21,SF,J. Johnson,NaN,NaN,NaN,NaN,NaN,0.378085,0.227465,-0.027689
565,2022,22,KC,P. Mahomes,0.551886,-0.171775,-0.113305,0.065889,0.593050,0.489216,-0.556909,-0.374081
566,2022,22,PHI,J. Hurts,0.023224,1.168924,0.715800,1.060234,-1.208004,0.996704,0.886268,-0.111853
567,2023,1,KC,P. Mahomes,1.067603,0.700516,-0.658311,-0.669019,0.041813,-0.301768,-0.241587,-0.450657
568,2023,1,DET,J. Goff,0.820262,-0.069032,0.060633,-0.222673,0.109899,0.495031,-0.037935,-0.335286

In [47]:
# NOTE: Pretty sure everything in previous code block is good, but do some checks next time i look at this

combined[combined.team=='LV'].tail(15)

,season,week,team,qb,passing_value,rushing_value,total_plays_standardized,total_possession_time_standardized,pass_percentage_standardized,pass_def_value,rush_def_value,special_teams_value
82,2022,3,LV,D. Carr,-0.354409,-0.127106,-0.345222,-0.287677,0.982883,0.006305,-0.953701,0.898321
114,2022,4,LV,D. Carr,0.084599,0.186347,0.037442,-0.072991,1.128654,-0.888879,-0.163986,0.218745
146,2022,5,LV,D. Carr,-0.162637,0.498625,0.976707,0.799641,0.261183,-0.385859,0.663661,-0.082727
204,2022,7,LV,D. Carr,0.290039,0.466815,-0.130699,0.007444,0.276317,-0.822949,0.207320,0.720074
232,2022,8,LV,D. Carr,0.791759,0.744807,0.234571,0.655166,-0.124869,-0.370542,-0.021695,0.468839
260,2022,9,LV,D. Carr,-0.411806,-0.861424,-0.420595,-0.348823,0.901039,-0.836893,0.143989,0.575088
287,2022,10,LV,D. Carr,0.386714,-0.538748,-0.403202,-0.240033,0.549215,-1.019773,0.185730,0.635252
316,2022,11,LV,D. Carr,0.177838,-0.865818,-0.432191,-0.166349,0.599308,-0.621012,-0.611838,1.151651
345,2022,12,LV,D. Carr,0.431588,-0.441359,-0.211870,0.142659,0.514440,-0.469932,-0.022517,0.683429
375,2022,13,LV,D. Carr,0.644733,-0.303888,0.640427,0.732129,-0.022556,-0.671993,0.371898,-0.011535
403,2022,14,LV,D. Carr,-0.069926,0.120165,-0.032134,0.133786,-0.232883,-0.092594,0.175335,0.481443
433,2022,15,LV,D. Carr,0.058132,0.220637,-0.078517,0.258972,-1.147112,-0.189959,0.820575,0.394005
465,2022,16,LV,D. Carr,-0.139032,0.206102,0.008452,0.498154,-0.147064,0.409822,0.158802,0.419900
495,2022,17,LV,J. Stidham,NaN,NaN,NaN,NaN,NaN,0.011940,0.489895,0.721520
527,2022,18,LV,J. Stidham,0.583818,-0.174906,0.292551,0.359467,-0.524781,-0.231787,-0.750364,0.731059

In [48]:
df[df.team == 'LV'].tail(15)

,index,Unnamed: 0,season,week,team,opponent,score,opponent_score,qb,passing_value,rushing_value,pass_def_value,rush_def_value,special_teams_value,total_plays_standardized,total_possession_time_standardized,pass_percentage_standardized,team_full,opponent_full
82,82,82.0,2022,3,LV,TEN,22.0,24.0,D. Carr,0.377271,0.395316,-1.485668,0.362491,-0.234306,0.292551,0.070133,1.225834,Las Vegas Raiders,Tennessee Titans
114,114,114.0,2022,4,LV,DEN,32.0,23.0,D. Carr,-0.324456,0.860762,0.113163,1.366152,-0.541308,2.031932,1.748271,-0.659443,Las Vegas Raiders,Denver Broncos
146,146,146.0,2022,5,LV,KC,29.0,30.0,D. Carr,0.722329,0.604470,-1.043071,-0.064839,1.255041,-0.751078,-0.361939,-0.113705,Las Vegas Raiders,Kansas City Chiefs
204,204,204.0,2022,7,LV,HOU,38.0,20.0,D. Carr,1.451418,0.997992,-0.263037,-0.144357,0.619986,0.060633,0.911131,-0.407904,Las Vegas Raiders,Houston Texans
232,232,232.0,2022,8,LV,NO,0.0,24.0,D. Carr,-1.486299,-2.454801,-1.007452,0.005009,0.742791,-1.098954,-1.226084,1.845282,Las Vegas Raiders,New Orleans Saints
260,260,260.0,2022,9,LV,JAX,20.0,27.0,D. Carr,0.704318,-0.933500,-1.472418,0.153001,0.718925,-0.751078,-0.662847,0.821846,Las Vegas Raiders,Jacksonville Jaguars
287,287,287.0,2022,10,LV,IND,20.0,25.0,D. Carr,0.155521,-1.035638,-0.236842,-1.229239,1.489781,-0.171284,0.124142,0.502799,Las Vegas Raiders,Indianapolis Colts
316,316,316.0,2022,11,LV,DEN,22.0,16.0,D. Carr,0.612199,-0.000614,-0.172988,0.305708,0.431690,0.060633,0.509921,0.344011,Las Vegas Raiders,Denver Broncos
345,345,345.0,2022,12,LV,SEA,40.0,34.0,D. Carr,1.215547,0.380761,-0.725063,0.989254,-0.891854,1.684056,1.651826,-0.832581,Las Vegas Raiders,Seattle Seahawks
375,375,375.0,2022,13,LV,LAC,27.0,20.0,D. Carr,-0.860145,0.520114,0.426079,0.177429,0.659193,-0.403202,-0.273210,-0.584123,Las Vegas Raiders,Los Angeles Chargers
403,403,403.0,2022,14,LV,LA,16.0,17.0,D. Carr,-0.143900,0.378262,-0.208257,1.475851,0.473515,-0.519160,-0.022454,-2.038574,Las Vegas Raiders,Los Angeles Rams
433,433,433.0,2022,15,LV,NE,30.0,24.0,D. Carr,-0.342400,0.066662,0.933908,-0.437372,0.592020,-0.055325,0.652659,0.590394,Las Vegas Raiders,New England Patriots
465,465,465.0,2022,16,LV,PIT,10.0,13.0,D. Carr,-0.575811,-0.763266,-0.134018,0.434909,1.169911,-1.446830,-0.716856,0.536983,Las Vegas Raiders,Pittsburgh Steelers
495,495,495.0,2022,17,LV,SF,34.0,37.0,J. Stidham,0.583818,-0.174906,-0.747105,-1.830646,0.706998,0.292551,0.359467,-0.524781,Las Vegas Raiders,San Francisco 49ers
527,527,527.0,2022,18,LV,KC,13.0,31.0,J. Stidham,-0.860391,-0.080724,-0.146029,-2.272334,0.139012,0.408510,0.872553,0.468105,Las Vegas Raiders,Kansas City Chiefs

In [49]:
# fix team names

combined['team_full'] = combined.apply(lambda x: fix_team_names(x, is_team=True), axis=1)
# combined['opponent_full'] = combined.apply(lambda x: fix_team_names(x, is_team=False), axis=1)
combined.head()

NameError: name 'fix_team_names' is not defined

In [ ]:
# Save aggregated data frame with values

combined.to_csv('data/05_value_models_aggregated.csv')

In [50]:
combined[(combined.team == 'BAL') & (combined.season==2022)]

,season,week,team,qb,passing_value,rushing_value,total_plays_standardized,total_possession_time_standardized,pass_percentage_standardized,pass_def_value,rush_def_value,special_teams_value
2,2022,1,BAL,L. Jackson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,2022,2,BAL,L. Jackson,0.447970,-0.212488,-1.330871,-0.682136,0.473307,0.634443,0.655233,1.591348
66,2022,3,BAL,L. Jackson,1.596948,-0.411663,-1.243902,-1.078523,-0.129374,-1.164932,-0.377815,1.306494
98,2022,4,BAL,L. Jackson,0.726285,1.175522,-0.878632,-0.410162,0.028713,-0.233519,-0.623527,0.968957
130,2022,5,BAL,L. Jackson,-0.140420,0.981079,-0.443787,0.652466,-0.333674,-0.207066,-0.207738,0.686375
162,2022,6,BAL,L. Jackson,-0.182345,0.725395,-0.368414,0.030398,-0.182606,0.226794,-0.395370,1.223545
190,2022,7,BAL,L. Jackson,-0.115538,1.281662,-0.443787,-0.133365,-0.108002,-0.696896,-0.010112,-0.018517
218,2022,8,BAL,L. Jackson,-0.638553,0.724956,-0.113305,0.504713,-1.265660,-0.107642,-0.440054,1.075591
247,2022,9,BAL,L. Jackson,-0.281026,1.146842,0.599841,1.131796,-0.483508,-0.369684,0.000090,0.967978
301,2022,11,BAL,L. Jackson,0.128256,0.839876,0.240369,1.185998,-1.224675,0.056966,0.240848,0.764531
329,2022,12,BAL,L. Jackson,-0.268221,0.399642,0.327338,0.882969,-0.584890,0.753200,0.422020,0.105162
360,2022,13,BAL,T. Huntley,NaN,NaN,NaN,NaN,NaN,-0.368397,1.145471,0.161253
390,2022,14,BAL,T. Huntley,-0.077535,0.286949,0.524468,0.471343,0.124769,0.000887,1.136501,0.018367
417,2022,15,BAL,T. Huntley,0.327203,0.389126,0.002654,0.558143,-1.574357,-0.147699,0.760412,0.627265
449,2022,16,BAL,T. Huntley,-0.975193,0.553212,-0.101709,-0.273982,-0.806858,0.138269,0.084235,0.133082
481,2022,17,BAL,T. Huntley,-0.469540,0.406969,-0.623523,-0.440059,-1.392336,-0.071568,0.958480,-0.081254
511,2022,18,BAL,A. Brown,NaN,NaN,NaN,NaN,NaN,-0.236354,-0.306089,0.660988
541,2022,19,BAL,T. Huntley,0.115134,-0.088201,-0.954006,-0.670562,-1.195987,0.242345,0.384028,0.330512

In [50]:
df[df.team == 'SF'].tail(15)

,season,week,team,opponent,score,opponent_score,qb,passing_value,rushing_value,pass_def_value,rush_def_value,special_teams_value,total_plays_standardized,total_possession_time_standardized,pass_percentage_standardized,team_full,opponent_full
4489,2022,6,SF,ATL,14,28,J. Garoppolo,0.150830,-2.791287,-1.014961,-0.508785,0.131760,-0.998939,-0.837163,1.226723,San Francisco 49ers,Atlanta Falcons
4516,2022,7,SF,KC,23,44,J. Garoppolo,0.087143,0.580775,-2.218665,-1.196759,1.248613,1.020090,0.764336,1.217384,San Francisco 49ers,Kansas City Chiefs
4546,2022,8,SF,LA,31,14,J. Garoppolo,1.600826,0.151594,0.054764,0.743690,0.408923,-1.447612,-0.088555,-0.300324,San Francisco 49ers,Los Angeles Rams
4599,2022,10,SF,LAC,22,16,J. Garoppolo,0.369584,0.220537,0.736455,-0.106955,-0.568912,0.795753,1.486873,-1.598667,San Francisco 49ers,Los Angeles Chargers
4628,2022,11,SF,ARI,38,10,J. Garoppolo,1.536268,1.026531,0.550368,0.747276,0.188465,-0.886771,-0.263603,-0.587765,San Francisco 49ers,Arizona Cardinals
4659,2022,12,SF,NO,13,0,J. Garoppolo,-0.001005,-0.190469,0.640552,1.454999,1.070847,0.347080,1.006423,-0.045922,San Francisco 49ers,New Orleans Saints
4689,2022,13,SF,MIA,33,17,B. Purdy,-0.053421,-0.126492,1.348306,-0.111838,0.470714,2.029605,2.324866,0.024851,San Francisco 49ers,Miami Dolphins
4716,2022,14,SF,TB,35,7,B. Purdy,1.089423,0.527490,0.606800,0.483648,1.237796,-0.774603,0.522249,-1.822974,San Francisco 49ers,Tampa Bay Buccaneers
4747,2022,15,SF,SEA,21,13,B. Purdy,0.651377,1.057992,1.113096,-0.261235,-2.123656,-0.438098,0.600462,-1.171305,San Francisco 49ers,Seattle Seahawks
4779,2022,16,SF,WAS,37,20,B. Purdy,0.791740,0.146685,-0.484144,2.863790,1.415588,-1.335444,-0.874407,-0.938109,San Francisco 49ers,Washington Football Team
4809,2022,17,SF,LV,37,34,B. Purdy,0.552776,2.237359,-0.452415,0.206605,-0.659282,0.010575,0.175878,-0.058037,San Francisco 49ers,Las Vegas Raiders
4841,2022,18,SF,ARI,38,13,B. Purdy,0.771077,-0.094765,1.819759,0.196554,0.633354,-0.438098,0.872344,-1.852352,San Francisco 49ers,Arizona Cardinals
4855,2022,19,SF,SEA,41,23,B. Purdy,2.023435,0.681747,-0.139021,-0.472432,0.568763,0.234912,0.544595,-0.845470,San Francisco 49ers,Seattle Seahawks
4864,2022,20,SF,DAL,19,12,B. Purdy,0.259976,-0.198592,0.602136,-0.358547,-0.563537,0.122744,0.570666,-0.920464,San Francisco 49ers,Dallas Cowboys
4868,2022,21,SF,PHI,7,31,J. Johnson,-0.560147,-2.345301,0.172187,-1.337421,0.597381,-2.344959,-1.734748,-1.160443,San Francisco 49ers,Philadelphia Eagles

In [51]:
offense_base[offense_base.team == 'SF']

      season  week team             qb
28      2014     1   SF  C. Kaepernick
60      2014     2   SF  C. Kaepernick
92      2014     3   SF  C. Kaepernick
118     2014     4   SF  C. Kaepernick
148     2014     5   SF  C. Kaepernick
...      ...   ...  ...            ...
4809    2022    17   SF       B. Purdy
4841    2022    18   SF       B. Purdy
4855    2022    19   SF       B. Purdy
4864    2022    20   SF       B. Purdy
4868    2022    21   SF     J. Johnson

[153 rows x 4 columns]

In [52]:
defense

      season  week team  pass_def_value  rush_def_value  special_teams_value
32      2014     2  ARI        0.027688        1.468394            -0.996743
33      2014     2  ATL       -0.559094       -1.005162            -0.243872
34      2014     2  BAL       -0.765953        0.727127            -0.442100
35      2014     2  BUF        0.504718       -0.187514             0.780553
36      2014     2  CAR        0.982581       -0.392165            -0.725290
...      ...   ...  ...             ...             ...                  ...
4866    2022    21   KC        0.667588       -0.924365            -0.554750
4867    2022    21  PHI        1.071502       -0.584493             0.282612
4868    2022    21   SF        0.459523        0.086384            -0.025820
4869    2022    22   KC        0.561616       -0.780062            -0.348834
4870    2022    22  PHI        1.027831        0.814121            -0.104304

[4839 rows x 6 columns]